package com.studiobrend.abraj.activity;

import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import java.util.Arrays;
import java.util.List;
import androidx.appcompat.widget.Toolbar;
import android.view.MenuItem;

import com.studiobrend.abraj.NameItem;
import com.studiobrend.abraj.NamesAdapter;
import com.studiobrend.abraj.R;

public class DevedesetDevetActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.devedesetdevet_activity);

        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        if (getSupportActionBar() != null) {
            getSupportActionBar().setTitle("99 NAMES OF ALLAH");
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
            getSupportActionBar().setDisplayShowHomeEnabled(true);
            getSupportActionBar().setHomeAsUpIndicator(R.drawable.arrow_left);
        }

        List<NameItem> nameItems = Arrays.asList(
                new NameItem(R.drawable.al_01_ar_rahmaan, R.raw.al_001, "Ar-Rahmaan\nThe Beneficent\n\n1:3 Most Gracious, Most Merciful;\n\nMeaning\nHe who wills goodness and mercy for all His creatures."),
                new NameItem(R.drawable.al_02_ar_raheem, R.raw.al_002, "Ar-Raheem\nThe Merciful\n\n2:163 And your Allah is One Allah. There is no god but He, Most Gracious, Most Merciful.\n\nMeaning\nHe who acts with extreme kindness."),
                new NameItem(R.drawable.al_03_al_malik, R.raw.al_003, "Al-Malik\nThe Eternal Lord\n\n20:114 High above all is Allah, the King, the Truth! Be not in haste with the Qur'an before its revelation to thee is completed, but say, \"O my Lord! advance me in knowledge.\"\n\nMeaning\nThe Sovereign Lord, The One with the complete Dominion, the One Whose Dominion is clear from imperfection"),
                new NameItem(R.drawable.al_04_al_quddus, R.raw.al_004, "Al-Quddus\nThe Most Sacred\n\n59:23 Allah is He, than Whom there is no other god;- the Sovereign, the Holy One, the Source of Peace (and Perfection), the Guardian of Faith, the Preserver of Safety, the Exalted in Might, the Irresistible, the Supreme: Glory to Allah. (High is He) above the partners they attribute to Him.\n\nMeaning\nThe One who is pure from any imperfection and clear from children and adversaries."),
                new NameItem(R.drawable.al_05_as_salam, R.raw.al_005, "As-Salam\nThe Embodiment of Peace\n\n59:23 Allah is He, than Whom there is no other god;- the Sovereign, the Holy One, the Source of Peace (and Perfection), the Guardian of Faith, the Preserver of Safety, the Exalted in Might, the Irresistible, the Supreme: Glory to Allah. (High is He) above the partners they attribute to Him.\n\nMeaning\nThe One who is free from every imperfection."),
                new NameItem(R.drawable.al_06_al_mumin, R.raw.al_006, "Al-Mu’min\nThe Infuser of Faith\n\n59:23 Allah is He, than Whom there is no other god;- the Sovereign, the Holy One, the Source of Peace (and Perfection), the Guardian of Faith, the Preserver of Safety, the Exalted in Might, the Irresistible, the Supreme: Glory to Allah. (High is He) above the partners they attribute to Him.\n\nMeaning\nThe One who witnessed for Himself that no one is God but Him. And He witnessed for His believers that they are truthful in their belief that no one is God but Him "),
                new NameItem(R.drawable.al_07_al_muhaymin, R.raw.al_007, "Al-Muhaymin\nThe Preserver of Safety\n\n59:23 Allah is He, than Whom there is no other god;- the Sovereign, the Holy One, the Source of Peace (and Perfection), the Guardian of Faith, the Preserver of Safety, the Exalted in Might, the Irresistible, the Supreme: Glory to Allah. (High is He) above the partners they attribute to Him.\n\nMeaning\nThe One who witnesses the saying and deeds of His creatures."),
                new NameItem(R.drawable.al_08_al_aziz, R.raw.al_008, "Al-Aziz\nThe Mighty One\n\n3:6 He it is Who shapes you in the wombs as He pleases. There is no god but He, the Exalted in Might, the Wise.\n\nMeaning\nThe Strong, The Defeater who is not defeated."),
                new NameItem(R.drawable.al_09_al_jabbar, R.raw.al_009, "Al-Jabbar\nThe Omnipotent One\n\n59:23 Allah is He, than Whom there is no other god;- the Sovereign, the Holy One, the Source of Peace (and Perfection), the Guardian of Faith, the Preserver of Safety, the Exalted in Might, the Irresistible, the Supreme: Glory to Allah. (High is He) above the partners they attribute to Him.\n\nMeaning\nThe One that nothing happens in His Dominion except that which He willed."),
                new NameItem(R.drawable.al_10_al_mutakabbir, R.raw.al_010, "Al-Mutakabbir\nThe Dominant One\n\n59:23 Allah is He, than Whom there is no other god;- the Sovereign, the Holy One, the Source of Peace (and Perfection), the Guardian of Faith, the Preserver of Safety, the Exalted in Might, the Irresistible, the Supreme: Glory to Allah. (High is He) above the partners they attribute to Him.\n\nMeaning\nThe One who is clear from the attributes of the creatures and from resembling them."),
                new NameItem(R.drawable.al_11_al_khaaliq, R.raw.al_011, "Al-Khaaliq\nThe Creator\n\n6:102 That is Allah, your Lord! there is no god but He, the Creator of all things: then worship ye Him: and He hath power to dispose of all affairs.\n\nMeaning\nThe One who brings everything from non-existence to existence."),
                new NameItem(R.drawable.al_12_al_baari, R.raw.al_012, "Al-Baari\nThe Evolver\n\n59:24 He is Allah, the Creator, the Evolver, the Bestower of Forms (or Colours). To Him belong the Most Beautiful Names: whatever is in the heavens and on earth, doth declare His Praises and Glory: and He is the Exalted in Might, the Wise.\n\nMeaning\nThe Maker, The Creator who has the Power to turn the entities."),
                new NameItem(R.drawable.al_13_al_musawwir, R.raw.al_013, "Al-Musawwir\nThe Flawless Shaper\n\n59:24 He is Allah, the Creator, the Evolver, the Bestower of Forms (or Colours). To Him belong the Most Beautiful Names: whatever is in the heavens and on earth, doth declare His Praises and Glory: and He is the Exalted in Might, the Wise.\n\nMeaning\nThe One who forms His creatures in different pictures."),
                new NameItem(R.drawable.al_14_al_ghaffaar, R.raw.al_014, "Al-Ghaffaar\nThe Great Forgiver\n\n20:82 \"But, without doubt, I am (also) He that forgives again and again, to those who repent, believe, and do right, who,- in fine, are ready to receive true guidance.\" \n\nMeaning\nThe Forgiver, The One who forgives the sins of His slaves time and time again."),
                new NameItem(R.drawable.al_15_al_qahhaar, R.raw.al_015, "Al-Qahhaar\nThe All-Prevailing Onen\n\n13:16 Say: \"Who is the Lord and Sustainer of the heavens and the earth?\" Say: \"(It is) Allah.\" Say: \"Do ye then take (for worship) protectors other than Him, such as have no power either for good or for harm to themselves?\" Say: \"Are the blind equal with those who see? Or the depths of darkness equal with light?\" Or do they assign to Allah partners who have created (anything) as He has created, so that the creation seemed to them similar? Say: \"(Allah) is the Creator of all things: He is the One, the Supreme and Irresistible.\"\n\nMeaning\nThe Dominant, The One who has the perfect Power and is not unable over anything."),
                new NameItem(R.drawable.al_16_al_wahhab, R.raw.al_016, "Al-Wahhab\nThe Supreme Bestower\n\n3:8 \"Our Lord!\" (they say), \"Let not our hearts deviate now after Thou hast guided us, but grant us mercy from Thine own Presence; for Thou art the Grantor of bounties without measure.\n\nMeaning\nThe One who is Generous in giving plenty without any return. He is everything that benefits whether Halal or Haram."),
                new NameItem(R.drawable.al_17_ar_razzaq, R.raw.al_017, "Ar-Razzaq\nThe Total Provider\n\n51:58 For Allah is He Who gives (all) Sustenance, Lord of Power, Steadfast (for ever).\n\nMeaning\nThe Sustainer, The Provider."),
                new NameItem(R.drawable.al_18_al_fattah, R.raw.al_018, "Al-Fattah\nThe Supreme Solver\n\n34:26 Say: \"Our Lord will gather us together and will in the end decide the matter between us (and you) in truth and justice: and He is the one to decide, the One Who knows all.\" \n\nMeaning\nThe Opener, The Reliever, The Judge, The One who opens for His slaves the closed worldly and religious matters."),
                new NameItem(R.drawable.al_19_al_alim, R.raw.al_019, "Al-Alim\nThe All-Knowing One\n\n2:158 Behold! Safa and Marwa are among the Symbols of Allah. So if those who visit the House in the Season or at other times, should compass them round, it is no sin in them. And if any one obeyeth his own impulse to good,- be sure that Allah is He Who recogniseth and knoweth.\n\nMeaning\nThe Knowledgeable; The One nothing is absent from His knowledge."),
                new NameItem(R.drawable.al_20_al_qaabid, R.raw.al_020, "Al-Qaabid\nThe Restricting One\n\n2:245 Who is he that will loan to Allah a beautiful loan, which Allah will double unto his credit and multiply many times? It is Allah that giveth (you) Want or plenty, and to Him shall be your return.\n\nMeaning\nThe Constrictor, The Withholder, The One who constricts the sustenance by His wisdom and expands and widens it with His Generosity and Mercy."),
                new NameItem(R.drawable.al_21_al_baasit, R.raw.al_021, "Al-Baasit\nThe Extender\n\n2:245 Who is he that will loan to Allah a beautiful loan, which Allah will double unto his credit and multiply many times? It is Allah that giveth (you) Want or plenty, and to Him shall be your return.\n\nMeaning\nThe Englarger, The One who constricts the sustenance by His wisdom and expands and widens it with His Generosity and Mercy."),
                new NameItem(R.drawable.al_22_al_khaafid, R.raw.al_022, "Al-Khaafid\nThe Reducer\n\n95:5 Then do We abase him (to be) the lowest of the low,...\n\nMeaning\nThe Abaser, The One who lowers whoever He willed by His Destruction and raises whoever He willed by His Endowment."),
                new NameItem(R.drawable.al_23_ar_rafi, R.raw.al_023, "Ar-Rafi\nThe Elevating One\n\n58:11 O ye who believe! When ye are told to make room in the assemblies, (spread out and) make room: (ample) room will Allah provide for you. And when ye are told to rise up, rise up Allah will rise up, to (suitable) ranks (and degrees), those of you who believe and who have been granted (mystic) Knowledge. And Allah is well- acquainted with all ye do.\n\nMeaning\nThe Exalter, The Elevator, The One who lowers whoever He willed by His Destruction and raises whoever He willed by His Endowment."),
                new NameItem(R.drawable.al_24_al_muizz, R.raw.al_024, "Al-Mu’izz\nThe Honourer-Bestower\n\n3:26 Say: \"O Allah. Lord of Power (And Rule), Thou givest power to whom Thou pleasest, and Thou strippest off power from whom Thou pleasest: Thou enduest with honour whom Thou pleasest, and Thou bringest low whom Thou pleasest: In Thy hand is all good. Verily, over all things Thou hast power.\n\nMeaning\nHe gives esteem to whoever He willed, hence there is no one to degrade Him; And He degrades whoever He willed, hence there is no one to give Him esteem."),
                new NameItem(R.drawable.al_25_al_muzil, R.raw.al_025, "Al-Muzil\nThe Abaser\n\n3:26 Say: \"O Allah. Lord of Power (And Rule), Thou givest power to whom Thou pleasest, and Thou strippest off power from whom Thou pleasest: Thou enduest with honour whom Thou pleasest, and Thou bringest low whom Thou pleasest: In Thy hand is all good. Verily, over all things Thou hast power.\n\nMeaning\nThe Dishonourer, The Humiliator, He gives esteem to whoever He willed, hence there is no one to degrade Him; And He degrades whoever He willed, hence there is no one to give Him esteem."),
                new NameItem(R.drawable.al_26_as_sami, R.raw.al_026, "As-Sami’\nThe All-Hearer\n\n2:17 Their similitude is that of a man who kindled a fire; when it lighted all around him, Allah took away their light and left them in utter darkness. So they could not see.\n\nMeaning\nThe Hearer, The One who Hears all things that are heard by His Eternal Hearing without an ear, instrument or organ."),
                new NameItem(R.drawable.al_27_al_baseer, R.raw.al_027, "Al-Baseer\nThe All-Seeing\n\n4:58 Allah doth command you to render back your Trusts to those to whom they are due; And when ye judge between man and man, that ye judge with justice: Verily how excellent is the teaching which He giveth you! For Allah is He Who heareth and seeth all things.\n\nMeaning\nThe All-Noticing, The One who Sees all things that are seen by His Eternal Seeing without a pupil or any other instrument."),
                new NameItem(R.drawable.al_28_al_hakam, R.raw.al_028, "Al-Hakam\nThe Impartial Judge\n\n22:69 \"(Allah) will judge between you on the Day of Judgment concerning the matters in which ye differ.\" \n\nMeaning\nThe Judge, He is the Ruler and His judgment is His Word."),
                new NameItem(R.drawable.al_29_al_adl, R.raw.al_029, "Al-Adl\nThe Embodiment of Justice\n\n6:115 The word of thy Lord doth find its fulfilment in truth and in justice: None can change His words: for He is the one who heareth and knoweth all.\n\nMeaning\nThe Just, The One who is entitled to do what He does."),
                new NameItem(R.drawable.al_30_al_lateef, R.raw.al_030, "Al-Lateef\nThe Knower of Subtleties\n\n6:103 No vision can grasp Him, but His grasp is over all vision: He is above all comprehension, yet is acquainted with all things.\n\nMeaning\nThe Subtle One, The Gracious, The One who is kind to His slaves and endows upon them."),
                new NameItem(R.drawable.al_31_al_khabeer, R.raw.al_031, "Al-Khabeer\nThe All-Aware One\n\n6:18 \"He is the irresistible, (watching) from above over His worshippers; and He is the Wise, acquainted with all things.\" \n\nMeaning\nThe One who knows the truth of things."),
                new NameItem(R.drawable.al_32_al_haleem, R.raw.al_032, "Al-Haleem\nThe Clement One\n\n2:225 Allah will not call you to account for thoughtlessness in your oaths, but for the intention in your hearts; and He is Oft-forgiving, Most Forbearing.\n\nMeaning\nThe Forebearing, The One who delays the punishment for those who deserve it and then He might forgive them."),
                new NameItem(R.drawable.al_33_al_azeem, R.raw.al_033, "Al-Azeem\nThe Magnificent One\n\n2:255 Allah. There is no god but He,-the Living, the Self-subsisting, Eternal. No slumber can seize Him nor sleep. His are all things in the heavens and on earth. Who is there can intercede in His presence except as He permitteth? He knoweth what (appeareth to His creatures as) before or after or behind them. Nor shall they compass aught of His knowledge except as He willeth. His Throne doth extend over the heavens and the earth, and He feeleth no fatigue in guarding and preserving them for He is the Most High, the Supreme (in glory).\n\nMeaning\nThe Great One, The Mighty, The One deserving the attributes of Exaltment, Glory, Extolement, and Purity from all imperfection."),
                new NameItem(R.drawable.al_34_al_ghafoor, R.raw.al_034, "Al-Ghafoor\nThe Great Forgiver\n\n2:173 He hath only forbidden you dead meat, and blood, and the flesh of swine, and that on which any other name hath been invoked besides that of Allah. But if one is forced by necessity, without wilful disobedience, nor transgressing due limits,- then is he guiltless. For Allah is Oft-forgiving Most Merciful.\n\nMeaning\nThe All-Forgiving, The Forgiving, The One who forgives a lot."),
                new NameItem(R.drawable.al_35_ash_shakoor, R.raw.al_035, "Ash-Shakoor\nThe Acknowledging One\n\n35:30 For He will pay them their meed, nay, He will give them (even) more out of His Bounty: for He is Oft-Forgiving, Most Ready to appreciate (service).\n\nMeaning\nThe Grateful, The Appreciative, The One who gives a lot of reward for a little obedience."),
                new NameItem(R.drawable.al_36_al_aliyy, R.raw.al_036, "Al-Aliyy\nThe Sublime One\n\n2:255 Allah. There is no god but He,-the Living, the Self-subsisting, Eternal. No slumber can seize Him nor sleep. His are all things in the heavens and on earth. Who is there can intercede in His presence except as He permitteth? He knoweth what (appeareth to His creatures as) before or after or behind them. Nor shall they compass aught of His knowledge except as He willeth. His Throne doth extend over the heavens and the earth, and He feeleth no fatigue in guarding and preserving them for He is the Most High, the Supreme (in glory).\n\nMeaning\nThe Most High, The One who is clear from the attributes of the creatures."),
                new NameItem(R.drawable.al_37_al_kabeer, R.raw.al_037, "Al-Kabeer\nThe Great One\n\n13:9 He knoweth the unseen and that which is open: He is the Great, the Most High.\n\nMeaning\nThe Most Great, The Great, The One who is greater than everything in status."),
                new NameItem(R.drawable.al_38_al_hafiz, R.raw.al_038, "Al-Hafiz\nThe Guarding One\n\n11:57 \"If ye turn away,- I (at least) have conveyed the Message with which I was sent to you. My Lord will make another people to succeed you, and you will not harm Him in the least. For my Lord hath care and watch over all things.\" \n\nMeaning\nThe Preserver, The Protector, The One who protects whatever and whoever He willed to protect."),
                new NameItem(R.drawable.al_39_al_muqeet, R.raw.al_039, "Al-Muqeet\nThe Sustaining One\n\n4:85 Whoever recommends and helps a good cause becomes a partner therein: And whoever recommends and helps an evil cause, shares in its burden: And Allah hath power over all things.\n\nMeaning\nThe Maintainer, The Guardian, The Feeder, The One who has the Power."),
                new NameItem(R.drawable.al_40_al_haseeb, R.raw.al_040, "Al-Haseeb\nThe Reckoning One\n\n4:6 Make trial of orphans until they reach the age of marriage; if then ye find sound judgment in them, release their property to them; but consume it not wastefully, nor in haste against their growing up. If the guardian is well-off, Let him claim no remuneration, but if he is poor, let him have for himself what is just and reasonable. When ye release their property to them, take witnesses in their presence: But all-sufficient is Allah in taking account.\n\nMeaning\nThe Reckoner, The One who gives the satisfaction."),
                new NameItem(R.drawable.al_41_al_jaleel, R.raw.al_041, "Al-Jaleel\nThe Majestic One\n\n55:27 But will abide (for ever) the Face of thy Lord,- full of Majesty, Bounty and Honour.\n\nMeaning\nThe Sublime One, The Beneficent, The One who is attributed with greatness of Power and Glory of status."),
                new NameItem(R.drawable.al_42_al_kareem, R.raw.al_042, "Al-Kareem\nThe Bountiful One\n\n27:40 Said one who had knowledge of the Book: \"I will bring it to thee within the twinkling of an eye!\" Then when (Solomon) saw it placed firmly before him, he said: \"This is by the Grace of my Lord!- to test me whether I am grateful or ungrateful! and if any is grateful, truly his gratitude is (a gain) for his own soul; but if any is ungrateful, truly my Lord is Free of all Needs, Supreme in Honour !\" \n\nMeaning\nThe Generous One, The Gracious, The One who is attributed with greatness of Power and Glory of status."),
                new NameItem(R.drawable.al_43_ar_raqeeb, R.raw.al_043, "Ar-Raqeeb\nThe Watchful One\n\n4:1 O mankind! reverence your Guardian-Lord, who created you from a single person, created, of like nature, his mate, and from them twain scattered (like seeds) countless men and women;- reverence Allah, through whom ye demand your mutual (rights), and (reverence) the wombs (That bore you): for Allah ever watches over you.\n\nMeaning\nThe Watcher, The One that nothing is absent from Him. Hence it’s meaning is related to the attribute of Knowledge."),
                new NameItem(R.drawable.al_44_al_mujeeb, R.raw.al_044, "Al-Mujeeb\nThe Responding One\n\n11:61 To the Thamud People (We sent) Salih, one of their own brethren. He said: \"O my people! Worship Allah. ye have no other god but Him. It is He Who hath produced you from the earth and settled you therein: then ask forgiveness of Him, and turn to Him (in repentance): for my Lord is (always) near, ready to answer.\" \n\nMeaning\nThe Responsive, The Hearkener, The One who answers the one in need if he asks Him and rescues the yearner if he calls upon Him."),
                new NameItem(R.drawable.al_45_al_waasi, R.raw.al_045, "Al-Waasi’\nThe All-Pervading One\n\n2:115 To Allah belong the east and the West: Whithersoever ye turn, there is the presence of Allah. For Allah is all-Pervading, all-Knowing.\n\nMeaning\nThe Vast, The All-Embracing, The Knowledgeable."),
                new NameItem(R.drawable.al_46_al_hakeem, R.raw.al_046, "Al-Hakeem\nThe Wise One\n\n2:129 \"Our Lord! send amongst them an Messenger of their own, who shall rehearse Thy Signs to them and instruct them in scripture and wisdom, and sanctify them: For Thou art the Exalted in Might, the Wise.\" \n\nMeaning\nThe Wise, The Judge of Judges, The One who is correct in His doings."),
                new NameItem(R.drawable.al_47_al_wadud, R.raw.al_047, "Al-Wadud\nThe Loving One\n\n11:90 \"But ask forgiveness of your Lord, and turn unto Him (in repentance): For my Lord is indeed full of mercy and loving-kindness.\" \n\nMeaning\nThe One who loves His believing slaves and His believing slaves love Him. His love to His slaves is His Will to be merciful to them and praise them."),
                new NameItem(R.drawable.al_48_al_majeed, R.raw.al_048, "Al-Majeed\nThe Glorious One\n\n11:73 They said: \"Dost thou wonder at Allah's decree? The grace of Allah and His blessings on you, o ye people of the house! for He is indeed worthy of all praise, full of all glory!\" \n\nMeaning\nThe Most Glorious One, The One who is with perfect Power, High Status, Compassion, Generosity and Kindness."),
                new NameItem(R.drawable.al_49_al_baith, R.raw.al_049, "Al-Ba’ith\nThe Infuser of New Life\n\n22:7 And verily the Hour will come: there can be no doubt about it, or about (the fact) that Allah will raise up all who are in the graves.\n\nMeaning\nThe Resurrector, The Raiser (from death), The One who resurrects His slaves after death for reward and/or punishment."),
                new NameItem(R.drawable.al_50_ash_shaheed, R.raw.al_050, "Ash-Shaheed\nThe All Observing Witness\n\n4:79 Whatever good, (O man!) happens to thee, is from Allah. but whatever evil happens to thee, is from thy (own) soul. and We have sent thee as an apostle to (instruct) mankind. And enough is Allah for a witness.\n\nMeaning\nThe Witness, The One who nothing is absent from Him."),
                new NameItem(R.drawable.al_51_al_haqq, R.raw.al_051, "Al-Haqq\nThe Embodiment of Truth\n\n6:62 Then are men returned unto Allah, their protector, the (only) reality: Is not His the command? and He is the swiftest in taking account.\n\nMeaning\nThe Truth, The True, The One who truly exists."),
                new NameItem(R.drawable.al_52_al_wakeel, R.raw.al_052, "Al-Wakeel\nThe Universal Trustee\n\n3:173 Men said to them: \"A great army is gathering against you\": And frightened them: But it (only) increased their Faith: They said: \"For us Allah sufficeth, and He is the best disposer of affairs.\" \n\nMeaning\nThe Trustee, The One who gives the satisfaction and is relied upon."),
                new NameItem(R.drawable.al_53_al_qawwiyy, R.raw.al_053, "Al-Qawwiyy\nThe Strong One\n\n22:40 (They are) those who have been expelled from their homes in defiance of right,- (for no cause) except that they say, \"our Lord is Allah.. Did not Allah check one set of people by means of another, there would surely have been pulled down monasteries, churches, synagogues, and mosques, in which the name of Allah is commemorated in abundant measure. Allah will certainly aid those who aid his (cause);- for verily Allah is full of Strength, Exalted in Might, (able to enforce His Will).\n\nMeaning\nThe Most Strong, The Strong, The One with the complete Power."),
                new NameItem(R.drawable.al_54_al_mateen, R.raw.al_054, "Al-Mateen\nThe Firm One\n\n51:58 For Allah is He Who gives (all) Sustenance,- Lord of Power,- Steadfast (for ever).\n\nMeaning\nThe One with extreme Power which is un-interrupted and He does not get tired."),
                new NameItem(R.drawable.al_55_al_waliyy, R.raw.al_055, "Al-Waliyy\nThe Protecting Associate\n\n3:68 Without doubt, among men, the nearest of kin to Abraham, are those who follow him, as are also this Messenger and those who believe: And Allah is the Protector of those who have faith.\n\nMeaning\nThe Protecting Friend, The Supporter."),
                new NameItem(R.drawable.al_56_al_hameed, R.raw.al_056, "Al-Hameed\nThe Sole-Laudable One\n\n14:1 A. L. R. A Book which We have revealed unto thee, in order that thou mightest lead mankind out of the depths of darkness into light - by the leave of their Lord - to the Way of (Him) the Exalted in power, worthy of all praise!\n\nMeaning\nThe Praiseworthy, The praised One who deserves to be praised."),
                new NameItem(R.drawable.al_57_al_muhsee, R.raw.al_057, "Al-Muhsee\nThe All-Enumerating One\n\n72:28 \"That He may know that they have (truly) brought and delivered the Messages of their Lord: and He surrounds (all the mysteries) that are with them, and takes account of every single thing.\" \n\nMeaning\nThe Counter, The Reckoner, The One who the count of things are known to him."),
                new NameItem(R.drawable.al_58_al_mubdi, R.raw.al_058, "Al-Mubdi\nThe Originator\n\n10:4 To Him will be your return- of all of you. The promise of Allah is true and sure. It is He Who beginneth the process of creation, and repeateth it, that He may reward with justice those who believe and work righteousness; but those who reject Him will have draughts of boiling fluids, and a penalty grievous, because they did reject Him.\n\nMeaning\nThe One who started the human being. That is, He created him."),
                new NameItem(R.drawable.al_59_al_mueed, R.raw.al_059, "Al-Mueed\nThe Restorer\n\n10:4 To Him will be your return- of all of you. The promise of Allah is true and sure. It is He Who beginneth the process of creation, and repeateth it, that He may reward with justice those who believe and work righteousness; but those who reject Him will have draughts of boiling fluids, and a penalty grievous, because they did reject Him.\n\nMeaning\nThe Reproducer, The One who brings back the creatures after death."),
                new NameItem(R.drawable.al_60_al_muhyi, R.raw.al_060, "Al-Muhyi\nThe Maintainer of life\n\n3:156 O ye who believe! Be not like the Unbelievers, who say of their brethren, when they are travelling through the Earth or engaged in fighting: \"If they had stayed with us, they would not have died, or been slain.\" This that Allah may make it a cause of sighs and regrets in their hearts. It is Allah that gives Life and Death, and Allah sees well all that ye do.\n\nMeaning\nThe Restorer, The Giver of Life, The One who took out a living human from semen that does not have a soul. He gives life by giving the souls back to the worn out bodies on the resurrection day and He makes the hearts alive by the light of knowledge."),
                new NameItem(R.drawable.al_61_al_mumeet, R.raw.al_061, "Al-Mumeet\nThe Inflictor of Death\n\n3:156 O ye who believe! Be not like the Unbelievers, who say of their brethren, when they are travelling through the Earth or engaged in fighting: \"If they had stayed with us, they would not have died, or been slain.\" This that Allah may make it a cause of sighs and regrets in their hearts. It is Allah that gives Life and Death, and Allah sees well all that ye do.\n\nMeaning\nThe Creator of Death, The Destroyer, The One who renders the living dead."),
                new NameItem(R.drawable.al_62_al_hayy, R.raw.al_062, "Al-Hayy\nThe Eternally Living One\n\n2:255 Allah. There is no god but He,-the Living, the Self-subsisting, Eternal. No slumber can seize Him nor sleep. His are all things in the heavens and on earth. Who is there can intercede in His presence except as He permitteth? He knoweth what (appeareth to His creatures as) before or after or behind them. Nor shall they compass aught of His knowledge except as He willeth. His Throne doth extend over the heavens and the earth, and He feeleth no fatigue in guarding and preserving them for He is the Most High, the Supreme (in glory).\n\nMeaning\nThe Alive, The One attributed with a life that is unlike our life and is not that of a combination of soul, flesh or blood."),
                new NameItem(R.drawable.al_63_al_qayyoom, R.raw.al_063, "Al-Qayyoom\nThe Self-Subsisting One\n\n2:255 Allah. There is no god but He,-the Living, the Self-subsisting, Eternal. No slumber can seize Him nor sleep. His are all things in the heavens and on earth. Who is there can intercede in His presence except as He permitteth? He knoweth what (appeareth to His creatures as) before or after or behind them. Nor shall they compass aught of His knowledge except as He willeth. His Throne doth extend over the heavens and the earth, and He feeleth no fatigue in guarding and preserving them for He is the Most High, the Supreme (in glory).\n\nMeaning\nThe One who remains and does not end."),
                new NameItem(R.drawable.al_64_al_waajid, R.raw.al_064, "Al-Waajid\nThe Pointing One\n\n38:44 \"And take in thy hand a little grass, and strike therewith: and break not (thy oath).\" Truly We found him full of patience and constancy. How excellent in Our service! ever did he turn (to Us)!\n\nMeaning\nThe Perceiver, The Finder, The Rich who is never poor. Al-Wajd is Richness."),
                new NameItem(R.drawable.al_65_al_maajid, R.raw.al_065, "Al-Maajid\nThe All-Noble One\n\n11:73 They said: \"Dost thou wonder at Allah's decree? The grace of Allah and His blessings on you, o ye people of the house! for He is indeed worthy of all praise, full of all glory!\" \n\nMeaning\nThe Glorious, He who is Most Glorious."),
                new NameItem(R.drawable.al_66_al_waahid, R.raw.al_066, "Al-Waahid\nThe Only One\n\n2:163 And your Allah is One Allah. There is no god but He, Most Gracious, Most Merciful.\n\nMeaning\nThe Unique, The One, The One without a partner."),
                new NameItem(R.drawable.al_67_al_ahad, R.raw.al_067, "Al-Ahad\nThe Sole One\n\n112:1 Say: He is Allah, the One and Only;\n\nMeaning\nThe One."),
                new NameItem(R.drawable.al_68_as_samad, R.raw.al_068, "As-Samad\nThe Supreme Provider\n\n112:2 Allah, the Eternal, Absolute;\n\nMeaning\nThe Eternal, The Independent, The Master who is relied upon in matters and reverted to in ones needs."),
                new NameItem(R.drawable.al_69_al_qaadir, R.raw.al_069, "Al-Qaadir\nThe Omnipotent One\n\n6:65 Say: \"He hath power to send calamities on you, from above and below, or to cover you with confusion in party strife, giving you a taste of mutual vengeance - each from the other.\" See how We explain the signs by various (symbols); that they may understand.\n\nMeaning\nThe Able, The Capable, The One attributed with Power."),
                new NameItem(R.drawable.al_70_al_muqtadir, R.raw.al_070, "Al-Muqtadir\nThe All Authoritative One\n\n18:45 Set forth to them the similitude of the life of this world: It is like the rain which we send down from the skies: the earth's vegetation absorbs it, but soon it becomes dry stubble, which the winds do scatter: it is (only) Allah who prevails over all things.\n\nMeaning\nThe Powerful, The Dominant, The One with the perfect Power that nothing is withheld from Him."),
                new NameItem(R.drawable.al_71_al_muqaddim, R.raw.al_071, "Al-Muqaddim\nThe Expediting One\n\n16:61 If Allah were to punish men for their wrong-doing, He would not leave, on the (earth), a single living creature: but He gives them respite for a stated Term: When their Term expires, they would not be able to delay (the punishment) for a single hour, just as they would not be able to anticipate it (for a single hour).\n\nMeaning\nThe Expediter, The Promoter, The One who puts things in their right places. He makes ahead what He wills and delays what He wills."),
                new NameItem(R.drawable.al_72_al_muakhkhir, R.raw.al_072, "Al-Mu’akhkhir\nThe Delayer\n\n71:4 \"So He may forgive you your sins and give you respite for a stated Term: for when the Term given by Allah is accomplished, it cannot be put forward: if ye only knew.\" \n\nMeaning\nThe Delayer, the Retarder, The One who puts things in their right places. He makes ahead what He wills and delays what He wills."),
                new NameItem(R.drawable.al_73_al_awwal, R.raw.al_073, "Al-Awwal\nThe Very First\n\n57:3 He is the First and the Last, the Evident and the Hidden: and He has full knowledge of all things.\n\nMeaning\nThe First, The One whose Existence is without a beginning."),
                new NameItem(R.drawable.al_74_al_akhir, R.raw.al_074, "Al-Akhir\nThe Infinite Last One\n\n57:3 He is the First and the Last, the Evident and the Hidden: and He has full knowledge of all things.\n\nMeaning\nThe Last, The One whose Existence is without an end."),
                new NameItem(R.drawable.al_75_az_zaahir, R.raw.al_075, "Az-Zaahir\nThe Perceptible\n\n57:3 He is the First and the Last, the Evident and the Hidden: and He has full knowledge of all things.\n\nMeaning\nThe Manifest, The One that nothing is above Him and nothing is underneath Him, hence He exists without a place. He, The Exalted, His Existence is obvious by proofs and He is clear from the delusions of attributes of bodies."),
                new NameItem(R.drawable.al_76_al_baatin, R.raw.al_076, "Al-Baatin\nThe Imperceptible\n\n57:3 He is the First and the Last, the Evident and the Hidden: and He has full knowledge of all things.\n\nMeaning\nThe Hidden, The One that nothing is above Him and nothing is underneath Him, hence He exists without a place. He, The Exalted, His Existence is obvious by proofs and He is clear from the delusions of attributes of bodies."),
                new NameItem(R.drawable.al_77_al_waali, R.raw.al_077, "Al-Waali\nThe Holder of Supreme Authority\n\n13:11 For each (such person) there are (angels) in succession, before and behind him: They guard him by command of Allah. Verily never will Allah change the condition of a people until they change it themselves (with their own souls). But when (once) Allah willeth a people's punishment, there can be no turning it back, nor will they find, besides Him, any to protect.\n\nMeaning\nThe Governor, The One who owns things and manages them."),
                new NameItem(R.drawable.al_78_al_mutaali, R.raw.al_078, "Al-Muta’ali\nThe Extremely Exalted One\n\n13:9 He knoweth the unseen and that which is open: He is the Great, the Most High.\n\nMeaning\nThe Most Exalted, The High Exalted, The One who is clear from the attributes of the creation."),
                new NameItem(R.drawable.al_79_al_barr, R.raw.al_079, "Al-Barr\nThe Fountain-Head of Truth\n\n52:28 \"Truly, we did call unto Him from of old: truly it is He, the Beneficent, the Merciful!\" \n\nMeaning\nThe Source of All Goodness, The Righteous, The One who is kind to His creatures, who covered them with His sustenance and specified whoever He willed among them by His support, protection, and special mercy."),
                new NameItem(R.drawable.al_80_at_tawwaab, R.raw.al_080, "At-Tawwaab\nThe Ever-Acceptor of Repentance\n\n2:37 Then learnt Adam from his Lord words of inspiration, and his Lord Turned towards him; for He is Oft-Returning, Most Merciful.\n\nMeaning\nThe Relenting, The One who grants repentance to whoever He willed among His creatures and accepts his repentance."),
                new NameItem(R.drawable.al_81_al_muntaqim, R.raw.al_081, "Al-Muntaqim\nThe Retaliator\n\n32:22 And who does more wrong than one to whom are recited the Signs of his Lord, and who then turns away therefrom? Verily from those who transgress We shall exact (due) Retribution.\n\nMeaning\nThe Avenger, The One who victoriously prevails over His enemies and punishes them for their sins. It may mean the One who destroys them."),
                new NameItem(R.drawable.al_82_al_afuww, R.raw.al_082, "Al-Afuww\nThe Supreme Pardoner\n\n4:99 For these, there is hope that Allah will forgive: For Allah doth blot out (sins) and forgive again and again.\n\nMeaning\nThe Forgiver, The One with wide forgiveness."),
                new NameItem(R.drawable.al_83_ar_raoof, R.raw.al_083, "Ar-Ra’oof\nThe Benign One\n\n3:30 \"On the Day when every soul will be confronted with all the good it has done, and all the evil it has done, it will wish there were a great distance between it and its evil. But Allah cautions you (To remember) Himself. And Allah is full of kindness to those that serve Him.\" \n\nMeaning\nThe Compassionate, The One with extreme Mercy. The Mercy of Allah is His will to endow upon whoever He willed among His creatures."),
                new NameItem(R.drawable.al_84_maalik_ul_mulk, R.raw.al_084, "Maalik-Ul-Mulk\nThe Eternal Possessor of Sovereignty\n\n3:26 Say: \"O Allah. Lord of Power (And Rule), Thou givest power to whom Thou pleasest, and Thou strippest off power from whom Thou pleasest: Thou enduest with honour whom Thou pleasest, and Thou bringest low whom Thou pleasest: In Thy hand is all good. Verily, over all things Thou hast power.\n\nMeaning\nThe One who controls the Dominion and gives dominion to whoever He willed."),
                new NameItem(R.drawable.al_85_zul_jalaali_wal_ikram, R.raw.al_085, "Zul-Jalaali-wal-Ikram\nThe Possessor of Majesty and Honour\n\n55:27 But will abide (for ever) the Face of thy Lord,- full of Majesty, Bounty and Honour.\n\nMeaning\nThe Lord of Majesty and Bounty, The One who deserves to be Exalted and not denied."),
                new NameItem(R.drawable.al_86_al_muqsit, R.raw.al_086, "Al-Muqsit\nThe Just One\n\n3:18 There is no god but He: That is the witness of Allah, His angels, and those endued with knowledge, standing firm on justice. There is no god but He, the Exalted in Power, the Wise.\n\nMeaning\nThe Equitable, The One who is Just in His judgment."),
                new NameItem(R.drawable.al_87_al_jaami, R.raw.al_087, "Al-Jaami’\nThe Assembler of Scattered Creations\n\n3:9 \"Our Lord! Thou art He that will gather mankind Together against a day about which there is no doubt; for Allah never fails in His promise.\" \n\nMeaning\nThe Gatherer, The One who gathers the creatures on a day that there is no doubt about, that is the Day of Judgment."),
                new NameItem(R.drawable.al_88_al_ghaniyy, R.raw.al_088, "Al-Ghaniyy\nThe Self-Sufficient One\n\n2:263 Kind words and the covering of faults are better than charity followed by injury. Allah is free of all wants, and He is Most-Forbearing.\n\nMeaning\nThe One who does not need the creation."),
                new NameItem(R.drawable.al_89_al_mughni, R.raw.al_089, "Al-Mughni\nThe Bestower of Sufficiency\n\n9:28 O ye who believe! Truly the Pagans are unclean; so let them not, after this year of theirs, approach the Sacred Mosque. And if ye fear poverty, soon will Allah enrich you, if He wills, out of His bounty, for Allah is All-knowing, All-wise.\n\nMeaning\nThe Enricher, The One who satisfies the necessities of the creatures."),
                new NameItem(R.drawable.al_90_al_maani, R.raw.al_090, "Al-Maani’\nThe Preventer\n\n67:21 Or who is there that can provide you with Sustenance if He were to withhold His provision? Nay, they obstinately persist in insolent impiety and flight (from the Truth).\n\nMeaning\nThe Withholder."),
                new NameItem(R.drawable.al_91_ad_daarr, R.raw.al_091, "Ad-Daarr\nThe Distressor\n\n7:17 \"Then will I assault them from before them and behind them, from their right and their left: Nor wilt thou find, in most of them, gratitude (for thy mercies).\" \n\nMeaning\nThe One who makes harm reach to whoever He willed and benefit to whoever He willed."),
                new NameItem(R.drawable.al_92_an_naafi, R.raw.al_092, "An-Naafi’\nThe Bestower of Benefits\n\nMeaning\nThe Creator of Good, The Propitious, The One who makes harm reach to whoever He willed and benefit to whoever He willed."),
                new NameItem(R.drawable.al_93_an_noor, R.raw.al_093, "An-Noor\nThe Prime Light\n\n24:35 Allah is the Light of the heavens and the earth. The Parable of His Light is as if there were a Niche and within it a Lamp: the Lamp enclosed in Glass: the glass as it were a brilliant star: Lit from a blessed Tree, an Olive, neither of the east nor of the west, whose oil is well-nigh luminous, though fire scarce touched it: Light upon Light! Allah doth guide whom He will to His Light: Allah doth set forth Parables for men: and Allah doth know all things.\n\nMeaning\nThe Light, The One who guides."),
                new NameItem(R.drawable.al_94_al_haadi, R.raw.al_094, "Al-Haadi\nThe Provider of Guidance\n\n25:31 Thus have We made for every prophet an enemy among the sinners: but enough is thy Lord to guide and to help.\n\nMeaning\nThe Guide, The One whom with His Guidance His believers were guided, and with His Guidance the living beings have been guided to what is beneficial for them and protected from what is harmful to them."),
                new NameItem(R.drawable.al_95_al_badi, R.raw.al_095, "Al-Badi’\nThe Unique One\n\n2:117 To Him is due the primal origin of the heavens and the earth: When He decreeth a matter, He saith to it: \"Be,\" and it is.\n\nMeaning\nThe Incomparable, The One who created the creation and formed it without any preceding example."),
                new NameItem(R.drawable.al_96_al_baaqi, R.raw.al_096, "Al-Baaqi\nThe Ever Surviving One\n\n55:27 But will abide (for ever) the Face of thy Lord,- full of Majesty, Bounty and Honour.\n\nMeaning\nThe Everlasting, The One that the state of non-existence is impossible for Him."),
                new NameItem(R.drawable.al_97_al_waaris, R.raw.al_097, "Al-Waaris\nThe Eternal Inheritor\n\n15:23 And verily, it is We Who give life, and Who give death: it is We Who remain inheritors (after all else passes away).\n\nMeaning\nThe Heir, The One whose Existence remains."),
                new NameItem(R.drawable.al_98_ar_rasheed, R.raw.al_098, "Ar-Rasheed\nThe Guide to Path of Rectitude\n\n11:97 Unto Pharaoh and his chiefs: but they followed the command of Pharaoh and the command of Pharaoh was no right (guide).\n\nMeaning\nThe Guide to the Right Path, The One who guides."),
                new NameItem(R.drawable.al_99_as_saboor, R.raw.al_099, "As-Saboor\nThe Extensively Enduring One\n\nMeaning\nThe Patient, The One who does not quickly punish the sinners.")

        );

        RecyclerView recyclerView = findViewById(R.id.recyclerView);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        NamesAdapter adapter = new NamesAdapter(nameItems, this, recyclerView);
        recyclerView.setAdapter(adapter);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if (item.getItemId() == android.R.id.home) {
            finish();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }
}